### ISSUE TITLE
No license is specified

### ISSUE THREAD

**Issue by fmguler** [kbullaughey/lstm-play#1]
I really like the way you implemented the whole LSTM sequence in a single nnGraph, but I can't find any license specified anywhere.

**Comment by kbullaughey** [comment]
I added the MIT License. I also merged in a branch where I've been doing most of my development of this, so you'll see a bunch of new (undocumented) stuff. Hopefully, I'll have time to update the tutorial. The lstm rock is turning into my main RNN library, and so it goes somewhat beyond the original purpose as a tutorial. Let me know if you have any questions.
